<a href="https://colab.research.google.com/github/AlisaLeibova/ML-study/blob/main/Copy_of_HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [11]:
import numpy as np
import random
vector = np.random.rand(10)
matrix = np.array([[11,14,17],
                      [20,23,26],
                      [29,32,35]])
print(f"Vector:\n{vector}")
print(f"Vector shape:\n{vector.shape}")
print(f"Matrix:\n{matrix}")
print(f"Matrix shape:\n{matrix.shape}")


Vector:
[0.76275972 0.34341335 0.09966374 0.97384037 0.43552586 0.71341221
 0.54100086 0.08333911 0.03784082 0.20098432]
Vector shape:
(10,)
Matrix:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Matrix shape:
(3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [21]:
vector_new = np.round((vector+10),2)
print(f"Vector new:\n{vector_new}")

matrix_new = matrix*2
print(f"Matrix new:\n{matrix_new}")

vector_square = np.round((vector_new*vector_new),2)
print(f"Vector square:\n{vector_square}")


Vector new:
[10.76 10.34 10.1  10.97 10.44 10.71 10.54 10.08 10.04 10.2 ]
Matrix new:
[[22 28 34]
 [40 46 52]
 [58 64 70]]
Vector square:
[115.78 106.92 102.01 120.34 108.99 114.7  111.09 101.61 100.8  104.04]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [22]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [27]:
result_matrix = np.dot(B,A)
display(result_matrix)

result_matrix_1 = np.dot(result_matrix,C)
display(result_matrix_1)

result_matrix_2 = np.dot(result_matrix,D)
display(result_matrix_2)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

array([[0.5202],
       [0.2846]])

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [37]:
result_matrix_T = result_matrix.T
display(result_matrix,result_matrix_T)
vector_T = np.round(vector.T,2)
display(vector_T)
#Змін в векторі післі транспонування нема

column_vector = np.round(np.expand_dims(vector,1),2)
display(column_vector)
# numpy.expand_dims перетворив vector в двумірну матрицю (в данному випадку в вектор стовбець)

column_vector_T = column_vector.T
display(np.round(column_vector_T,2))
# транспонування перетворило вектор строку в вектор стовбець

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

array([0.76, 0.34, 0.1 , 0.97, 0.44, 0.71, 0.54, 0.08, 0.04, 0.2 ])

array([[0.76],
       [0.34],
       [0.1 ],
       [0.97],
       [0.44],
       [0.71],
       [0.54],
       [0.08],
       [0.04],
       [0.2 ]])

array([[0.76, 0.34, 0.1 , 0.97, 0.44, 0.71, 0.54, 0.08, 0.04, 0.2 ]])